[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[window]
padding = { x = 10, y = 10}

[font]
size = 14.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[terminal]
shell = { program = "/bin/zsh", args = [] }
